CREATE TABLE ADMIN_DETAILS
(
	FULLNAME VARCHAR2(30),
	USERID VARCHAR2(20) UNIQUE,
	SECURITYQUESTION VARCHAR2(50),
	ANSWER VARCHAR2(20),
	PASSWORD VARCHAR2(20)
);

CREATE TABLE EMPLOYEE_DETAILS
(
	ID VARCHAR2(20) PRIMARY KEY,
	NAME VARCHAR2(30),
	DOB DATE,
	GENDER VARCHAR2(20),
	MOBILE_NO VARCHAR2(13),
	EMAILID VARCHAR2(50),
	ADDRESS VARCHAR2(100),
	USERID VARCHAR2(30) UNIQUE,
	SECURITY_QUESTION VARCHAR2(50),
	ANSWER VARCHAR2(30),
	PASSWORD VARCHAR2(30)
);

CREATE TABLE AUTHOR_DETAILS
(
	ID VARCHAR2(30) PRIMARY KEY,
	NAME VARCHAR2(50) UNIQUE
);

CREATE TABLE PUBLISHER_DETAILS
(
	ID VARCHAR2(20) PRIMARY KEY,
	NAME VARCHAR2(50) UNIQUE
);

CREATE TABLE BOOK_DETAILS
(
	ID VARCHAR2(30) PRIMARY KEY,
	NAME VARCHAR2(50),
	AUTHOR VARCHAR2(500),
	PUBLICATION VARCHAR2(50),
	TYPE VARCHAR2(30),
	STOCK NUMBER,
	PRICE NUMBER,
	FOREIGN KEY(AUTHOR) REFERENCES AUTHOR_DETAILS(NAME),
	FOREIGN KEY(PUBLICATION) REFERENCES PUBLISHER_DETAILS(NAME)
);

CREATE TABLE SALE_DETAILS
(
	Sale_Date Date,
	ID VARCHAR(30) PRIMARY KEY,
	CUSTOMER VARCHAR(30),
	MOBILE_NO NUMBER(10),
	ADDRESS VARCHAR2(50),
	BOOK VARCHAR2(100),
	NOOFBOOK NUMBER(10),
	TOTAL_PRICE NUMBER(10),
	SALEBY VARCHAR2(30)
);

INSERT INTO ADMIN_DETAILS VALUES('ADMINISTRATOR','admin','FAVOURITE COLOR','BLUE','admin');

COMMIT;
\
QUIT
\





